/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Folder = (string | null)
export type Captionprefix = string
export type Image = string
export type Caption = string
export type Captionstr = string
export type Items = DatasetItem[]
export type RootModelNoneType = null
export type Current = string
export type Tool = (BrushTool | RectTool | SplitTool | TrimTool | ExpandTool | ViewTool | ConcatTool)
export type Id = "brush"
export type Color = string
export type Width = number
export type X = number
export type Y = number
export type Points = Point[]
export type Drawing = BrushState[]
export type Id1 = "rect"
export type Color1 = string
export type Drawing1 = RectState[]
export type Id2 = "split"
export type Mode = ("cross" | "horizontal" | "vertical")
export type Id3 = "trim"
export type Top = number
export type Bottom = number
export type Left = number
export type Right = number
export type Id4 = "expand"
export type Color2 = string
export type Top1 = number
export type Bottom1 = number
export type Left1 = number
export type Right1 = number
export type Id5 = "view"
export type Id6 = "concat"
export type Mode1 = ("horizontal" | "vertical")
export type Image1 = string
export type Offset = number
export type Color3 = string
export type Caption1 = string
export type Captionprefix1 = string
export type RootModelUnionStrNoneType = (string | null)
export type RootModelStr = string
export type Op = ("escape_parentheses" | "unescape_parentheses")
export type RootModelListStr = string[]

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
get_state: {
input: void | undefined
output: AppState
}
close_folder: {
input: void | undefined
output: RootModelNoneType
}
save: {
input: SaveArgs
output: RootModelUnionStrNoneType
}
delete_item: {
input: RootModelStr
output: RootModelNoneType
}
batch_operation: {
input: BatchOperationPayload
output: RootModelNoneType
}
on_drag: {
input: RootModelListStr
output: RootModelStr
}
open_folder: {
input: RootModelStr
output: RootModelNoneType
}
}
export interface AppState {
folder?: Folder
captionPrefix?: Captionprefix
items?: Items
}
export interface DatasetItem {
image: Image
caption: Caption
captionStr: Captionstr
}
export interface SaveArgs {
current: Current
tool: Tool
caption: Caption1
captionPrefix: Captionprefix1
}
export interface BrushTool {
id: Id
drawing: Drawing
}
export interface BrushState {
color: Color
width: Width
points: Points
}
export interface Point {
x: X
y: Y
}
export interface RectTool {
id: Id1
drawing: Drawing1
}
export interface RectState {
color: Color1
start: Point
end: Point
}
export interface SplitTool {
id: Id2
mode: Mode
point: Point
}
export interface TrimTool {
id: Id3
top: Top
bottom: Bottom
left: Left
right: Right
}
export interface ExpandTool {
id: Id4
color: Color2
top: Top1
bottom: Bottom1
left: Left1
right: Right1
}
export interface ViewTool {
id: Id5
}
export interface ConcatTool {
id: Id6
mode: Mode1
image: Image1
offset: Offset
color: Color3
}
export interface BatchOperationPayload {
op: Op
}
