/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Folder = (string | null)
export type Captionprefix = string
export type Image = string
export type Caption = string
export type Captionstr = string
export type Items = DatasetItem[]
export type RootModelNoneType = null
export type Current = string
export type Tool = (BrushTool | RectTool | SplitTool | TrimTool | ExpandTool | ViewTool | ConcatTool)
export type Id = "brush"
export type Color = string
export type Width = number
export type X = number
export type Y = number
export type Points = Point[]
export type Drawing = BrushState[]
export type Id1 = "rect"
export type Color1 = string
export type Drawing1 = RectState[]
export type Id2 = "split"
export type Mode = ("cross" | "horizontal" | "vertical")
export type Id3 = "trim"
export type Top = number
export type Bottom = number
export type Left = number
export type Right = number
export type Id4 = "expand"
export type Color2 = string
export type Top1 = number
export type Bottom1 = number
export type Left1 = number
export type Right1 = number
export type Id5 = "view"
export type Id6 = "concat"
export type Mode1 = ("horizontal" | "vertical")
export type Image1 = string
export type Offset = number
export type Color3 = string
export type Caption1 = string
export type Captionprefix1 = string
export type RootModelUnionStrNoneType = (string | null)
export type RootModelStr = string
export type RootModelBatchOperationPayload = (EscapeOperation | UnescapeOperation | AlignResolutionOperation | DeduplicateTagsOperation | ReplaceTagsOperation | RemoveTagsOperation | RemoveTransparencyOperation)
export type Id7 = "escape_parentheses"
export type Id8 = "unescape_parentheses"
export type Id9 = "align_resolution"
export type Width1 = number
export type Height = number
export type Color4 = string
export type Boxtag = boolean
export type Position = ("top-left" | "top-center" | "top-right" | "center-left" | "center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right")
export type Id10 = "deduplicate_tags"
export type Id11 = "replace_tags"
export type Find = string
export type Replace = string
export type Id12 = "remove_tags"
export type Tags = string[]
export type Id13 = "remove_transparency"
export type Color5 = string
export type RootModelListStr = string[]

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
get_state: {
input: void | undefined
output: AppState
}
close_folder: {
input: void | undefined
output: RootModelNoneType
}
save: {
input: SaveArgs
output: RootModelUnionStrNoneType
}
delete_item: {
input: RootModelStr
output: RootModelNoneType
}
batch_operation: {
input: RootModelBatchOperationPayload
output: RootModelNoneType
}
on_drag: {
input: RootModelListStr
output: RootModelStr
}
open_folder: {
input: RootModelStr
output: RootModelNoneType
}
}
export interface AppState {
folder?: Folder
captionPrefix?: Captionprefix
items?: Items
}
export interface DatasetItem {
image: Image
caption: Caption
captionStr: Captionstr
}
export interface SaveArgs {
current: Current
tool: Tool
caption: Caption1
captionPrefix: Captionprefix1
}
export interface BrushTool {
id: Id
drawing: Drawing
}
export interface BrushState {
color: Color
width: Width
points: Points
}
export interface Point {
x: X
y: Y
}
export interface RectTool {
id: Id1
drawing: Drawing1
}
export interface RectState {
color: Color1
start: Point
end: Point
}
export interface SplitTool {
id: Id2
mode: Mode
point: Point
}
export interface TrimTool {
id: Id3
top: Top
bottom: Bottom
left: Left
right: Right
}
export interface ExpandTool {
id: Id4
color: Color2
top: Top1
bottom: Bottom1
left: Left1
right: Right1
}
export interface ViewTool {
id: Id5
}
export interface ConcatTool {
id: Id6
mode: Mode1
image: Image1
offset: Offset
color: Color3
}
export interface EscapeOperation {
id: Id7
}
export interface UnescapeOperation {
id: Id8
}
export interface AlignResolutionOperation {
id: Id9
width: Width1
height: Height
color: Color4
boxTag: Boxtag
position: Position
}
export interface DeduplicateTagsOperation {
id: Id10
}
export interface ReplaceTagsOperation {
id: Id11
find: Find
replace: Replace
}
export interface RemoveTagsOperation {
id: Id12
tags: Tags
}
export interface RemoveTransparencyOperation {
id: Id13
color: Color5
}
