/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function getState(
    body: Commands["get_state"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_state"]["output"]> {
    return await pyInvoke("get_state", body, options);
}

export async function closeFolder(
    body: Commands["close_folder"]["input"],
    options?: InvokeOptions
): Promise<Commands["close_folder"]["output"]> {
    return await pyInvoke("close_folder", body, options);
}

export async function save(
    body: Commands["save"]["input"],
    options?: InvokeOptions
): Promise<Commands["save"]["output"]> {
    return await pyInvoke("save", body, options);
}

export async function setPrefix(
    body: Commands["set_prefix"]["input"],
    options?: InvokeOptions
): Promise<Commands["set_prefix"]["output"]> {
    return await pyInvoke("set_prefix", body, options);
}

export async function deleteItem(
    body: Commands["delete_item"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_item"]["output"]> {
    return await pyInvoke("delete_item", body, options);
}

export async function batchOperation(
    body: Commands["batch_operation"]["input"],
    options?: InvokeOptions
): Promise<Commands["batch_operation"]["output"]> {
    return await pyInvoke("batch_operation", body, options);
}

export async function onDrag(
    body: Commands["on_drag"]["input"],
    options?: InvokeOptions
): Promise<Commands["on_drag"]["output"]> {
    return await pyInvoke("on_drag", body, options);
}

export async function openFolder(
    body: Commands["open_folder"]["input"],
    options?: InvokeOptions
): Promise<Commands["open_folder"]["output"]> {
    return await pyInvoke("open_folder", body, options);
}
