/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function getState(
    body: Commands["get_state"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_state"]["output"]> {
    return await pyInvoke("get_state", body, options);
}

export async function closeFolder(
    body: Commands["close_folder"]["input"],
    options?: InvokeOptions
): Promise<Commands["close_folder"]["output"]> {
    return await pyInvoke("close_folder", body, options);
}

export async function save(
    body: Commands["save"]["input"],
    options?: InvokeOptions
): Promise<Commands["save"]["output"]> {
    return await pyInvoke("save", body, options);
}

export async function selectFolder(
    body: Commands["select_folder"]["input"],
    options?: InvokeOptions
): Promise<Commands["select_folder"]["output"]> {
    return await pyInvoke("select_folder", body, options);
}
